# -*- coding: utf-8 -*-
"""numeros_primos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QzEIe-uEmFTeVyph8buzXCWM_dgDaFek
"""

candidato = int(input("Digite um número : \n"))
contador = 1
contaDiv = 0

print(f"O número {candidato} é divisível por: \n ")

while contador <= candidato:
     if candidato % contador == 0:
        print(contador)
        contaDiv += 1

     contador += 1

print(f"\n Total de divisores é : {contaDiv}")

if contaDiv == 2 :
  print(f"O número {candidato} é primo")
else:
  print(f"O número {candidato} não é primo")

  #Hoje estudei como achar os números primos com o Curso da EBAC